# Generated by Django 4.0.1 on 2022-10-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogManage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
